# List of blacklisted countries
blacklisted-countries:
  - Russia
  - Iran
  - China
kick-message: '{ "text": "Sorry, players from your country are not allowed on this server.", "extra": [ { "text": "\n\nК сожалению, игроки из вашей страны не допускаются на этот сервер.", "color": "white", "bold": true } ], "color": "white", "bold": true }'