name: JustBanTheCountry
version: '${version}'
main: org.opencommunity.JustBanTheCountry.Main
api-version: 1.19
depend: [EssentialsGeoIP]

authors: [Envel]
description: Just Ban The Country

commands:
  cwhitelist:
    usage: /cwhitelist <add|remove> <player>
    description: Manage the whitelist
    permission: justbanthecountry.usage
permissions:
   justbanthecountry.usage:
    description: Permission to manage whitelist
    default: op